"""Generate a TypeScript alt-text module from the image/video manifests.

Outputs src/lib/stock-media.ts with typed maps:
  STOCK_IMAGES: Record<filename, { alt, category, tags, credit }>
  STOCK_VIDEOS: Record<filename, { alt, category, poster, credit }>

Use in components like:
  import { STOCK_IMAGES } from '@/lib/stock-media'
  const img = STOCK_IMAGES['maxlife-office-buildings-...-1044807.webp']
  <Image src={`/images/commercial-stock/office-buildings/${filename}`} alt={img.alt} ... />
"""
import json
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
IMAGES_MANIFEST = PROJECT / "public" / "images" / "commercial-stock" / "_manifest.json"
VIDEOS_MANIFEST = PROJECT / "assets" / "videos" / "commercial-stock" / "_manifest.json"
OUT = PROJECT / "src" / "lib" / "stock-media.ts"

CATEGORY_PHRASES = {
    "office-buildings": "Modern office building",
    "retail-storefronts": "Retail storefront",
    "warehouse": "Commercial warehouse",
    "commercial-business": "Commercial business property",
    "real-estate-development": "Real estate development site",
    "mixed-commercial": "Commercial real estate",
}


def build_alt(entry: dict) -> str:
    cat = entry["category"]
    phrase = CATEGORY_PHRASES.get(cat, cat.replace("-", " ").title())
    tags = entry.get("tags", "")
    # take first 3 meaningful tag phrases
    parts = [t.strip() for t in tags.split(",") if t.strip()][:3]
    tag_text = ", ".join(parts) if parts else ""
    if tag_text:
        return f"{phrase} — {tag_text}"
    return phrase


def main():
    images = {}
    if IMAGES_MANIFEST.exists():
        for e in json.loads(IMAGES_MANIFEST.read_text()):
            fname = Path(e["file"]).name
            images[fname] = {
                "category": e["category"],
                "alt": build_alt(e),
                "tags": e.get("tags", ""),
                "credit": f"Photo by {e.get('user','Pixabay')} via Pixabay",
                "source": e.get("page_url", ""),
            }

    videos = {}
    if VIDEOS_MANIFEST.exists():
        for e in json.loads(VIDEOS_MANIFEST.read_text()):
            fname = Path(e["file"]).name
            videos[fname] = {
                "category": e["category"],
                "alt": build_alt(e),
                "tags": e.get("tags", ""),
                "duration": e.get("duration", 0),
                "poster": e.get("poster", ""),
                "credit": f"Video by {e.get('user','Pixabay')} via Pixabay",
                "source": e.get("page_url", ""),
            }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "// AUTO-GENERATED by scripts/build_alt_manifest.py — do not edit by hand.\n"
        "// Source: public/images/commercial-stock/_manifest.json +\n"
        "//         assets/videos/commercial-stock/_manifest.json\n\n"
    )
    ts = header
    ts += "export type StockImage = {\n"
    ts += "  category: string\n  alt: string\n  tags: string\n  credit: string\n  source: string\n}\n\n"
    ts += "export type StockVideo = {\n"
    ts += "  category: string\n  alt: string\n  tags: string\n  duration: number\n  poster: string\n  credit: string\n  source: string\n}\n\n"
    ts += f"export const STOCK_IMAGES: Record<string, StockImage> = {json.dumps(images, indent=2)} as const\n\n"
    ts += f"export const STOCK_VIDEOS: Record<string, StockVideo> = {json.dumps(videos, indent=2)} as const\n\n"
    ts += "export const STOCK_IMAGES_BY_CATEGORY: Record<string, string[]> = (() => {\n"
    ts += "  const out: Record<string, string[]> = {}\n"
    ts += "  for (const [f, m] of Object.entries(STOCK_IMAGES)) {\n"
    ts += "    (out[m.category] ??= []).push(f)\n"
    ts += "  }\n"
    ts += "  return out\n"
    ts += "})()\n\n"
    ts += "export const STOCK_VIDEOS_BY_CATEGORY: Record<string, string[]> = (() => {\n"
    ts += "  const out: Record<string, string[]> = {}\n"
    ts += "  for (const [f, m] of Object.entries(STOCK_VIDEOS)) {\n"
    ts += "    (out[m.category] ??= []).push(f)\n"
    ts += "  }\n"
    ts += "  return out\n"
    ts += "})()\n"
    OUT.write_text(ts, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"  images: {len(images)}")
    print(f"  videos: {len(videos)}")


if __name__ == "__main__":
    main()
